# https://github.com/camunda-community-hub/spring-zeebe#configuring-camunda-platform-8-saas-connection
# https://github.com/camunda-community-hub/spring-zeebe#additional-configuration-options

keycloak:
  enabled: false
#  auth-server-url: http://localhost:18080/auth
#  realm: camunda-platform
#  resource: ConnectorRuntime
#  public-client: true
#  principal-attribute: preferred_username
  
zeebe.client.cloud:
  region: bru-2
  clusterId: 3e546037-a61a-4ca6-a9ff-190d77e80eff
  clientId: KH-~bAWGbeyX_0Ow1jLyvsyluPO8I800
  clientSecret: CTSTGyI_1xI1MEH.m_Du.2f6PHXIvNH5-BXb~Yf4o0DX0SvH4BUQmrhYnSLiPMb7
  
#zeebe.client:
#  broker.gatewayAddress: 127.0.0.1:26500
#  security.plaintext: true

#identity.clientId: pouet
#identity.clientSecret: M9vS2AT5fNgZ3lcUjcdXKVJgSBiApQ4t
#keycloakUrl: http://localhost:18080
#operateUrl: http://localhost:8081/

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB
server:
  port: 8086
  socketPort: 5000
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
